### ISSUE TITLE
Parallelization

### ISSUE THREAD

**Issue by Ploppz** [TLmaK0/rustneat#33]
I could not find any thread parallelization in the code, please correct me if I'm wrong.
How should this be done? I'm willing to do the work.
What I'm thinking is just parallelize the calls to `Environment::test` for evaluating fitness. This is most important to me, as my fitness calculation can be quite heavy.
I suggest using `rayon`. Any thoughts?

**Comment by TLmaK0** [comment]
Hi @Ploppz, there is a parallelization in https://github.com/TLmaK0/rustneat/blob/7c58287704a1e37b81abd0861e8b1e443893569b/src/species_evaluator.rs#L26
where the organisms are evaluated in parallel, but If you have any idea to improve the environment test feel free to create a pull request, any help will be appreciated.
Use function_approximation branch because there are a lot of fix there but doesn't pass the tests.

**Comment by Ploppz** [comment]
Thanks!
